version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu2204
build_script:
- sh: >-
    cd util/linux/build
    libtoolize
    aclocal
    automake --add-missing --ignore-deps
    autoconf
    ./configure
    make
artifacts:
- path: util/linux/build/libmlutil/.libs/libmlutil.so
  name: mle-core-util