# Version format
version: 1.0.{build}

# Branches to build
branches:
  only:
  - master

# Build worker image
image:
  - Ubuntu2204

# Set environmnet
environment:
    MLE_ROOT: /opt/MagicLantern

# Custom script to build libmlutil.so using autoconf tools.
build_script:
- sh: >-
    printf "Building Ubuntu 22.04 Linux library\n";
    cd util/linux/build;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make
- sh: >-
    printf "Installing Ubuntu 22.04 Linux library\n";
    sudo mkdir $MLE_ROOT;
    sudo MLE_ROOT=$MLE_ROOT make install

# Custom script to create an .zip file containing the libmlutil artifacts.
after_build:
- sh: >-
    cd /home/appveyor/projects/mle-core-util;
    7z a mlutil.zip $MLE_ROOT

# Define artifacts to push to AppVeyor
artifacts:
- path: mlutil.zip
  name: mle-core-util
