# COPYRIGHT_BEGIN
#
# The MIT License (MIT)
#
# Copyright (c) 2025 Wizzer Works
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#  For information concerning this header file, contact Mark S. Millard,
#  of Wizzer Works at msm@wizzerworks.com.
#
#  More information concerning Wizzer Works may be found at
#
#      http://www.wizzerworks.com
#
# COPYRIGHT_END

# Version format
version: 1.0.{build}

# Branches to build
branches:
  only:
  - master

# Build worker image
image:
  - Visual Studio 2022

# Set environmnet
environment:
    MLE_ROOT: C:\opt\MagicLantern
    MLE_HOME: C:\opt\MagicLantern

# Build platform
platform: x64

# Build Configuration
configuration:
  - Debug
  - Release

# MSBuild settings
build:
    project: util\win32\build\msvc17\mleutil.sln

# Custom script to create an .zip file containing the util.lib artifacts.
after_build:
  - ps: |
      if ($env:configuration -eq "Debug") {7z a mlutil-debug.zip %MLE_ROOT%}
      if ($env:configuration -eq "Release") {7z a mlutil-release.zip %MLE_ROOT%}

# Define artifacts to push to AppVeyor
artifacts:
- path: mlutil.zip
  name: mle-core-util-windows
