version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu2204

# Custom script to build libmlutil.so using autoconf tools.
build_script:
- sh: >-
    cd util/linux/build;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make

# Custom script to create an .zip file containing the libmlutil artifacts.
after_build:
    7z a mlutil.zip util/linux/build/libmlutil/.libs/libmlutil.so

# Define artifacts to push to AppVeyor
artifacts:
- path: mlutil.zip
  name: mle-core-util
