version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu2204

# Set environmnet
environment:
    MLE_ROOT: /opt/MagicLantern

# Custom script to build libmlutil.so using autoconf tools.
build_script:
- sh: >-
    cd util/linux/build;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make
- sh: >-
    sudo mkdir $MLE_ROOT;
    sudo make install

# Custom script to create an .zip file containing the libmlutil artifacts.
after_build:
    7z a mlutil.zip $MLE_ROOT

# Define artifacts to push to AppVeyor
artifacts:
- path: util/linux/build/mlutil.zip
  name: mle-core-util
