# Version format
version: 1.0.{build}

# Branches to build
branches:
  only:
  - master

# Build worker image
image:
  - Visual Studio 2017

# Set environmnet
environment:
    MLE_ROOT: C:\opt\MagicLantern

# Build platform
platform: x64

# Build Configuration
configuration: Debug Release

# MSBuild settings
build:
    project: util\win32\build\msvc15\mleutil.sln

# Custom script to create an .zip file containing the util.lib artifacts.
after_build:
- sh: >-
    cd %MLE_ROOT%;
    7z a mlutil.zip %MLE_ROOT%

# Define artifacts to push to AppVeyor
artifacts:
- path: mlutil.zip
  name: mle-core-util-windows
